# Generated by Django 5.1.7 on 2025-04-03 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='post.category'),
            preserve_default=False,
        ),
    ]
