# Generated by Django 5.2 on 2025-04-18 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_view_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='view_count',
            new_name='views_count',
        ),
    ]
