texts = {
    'uzbek': {
        'welcome_morning': "Hayrli tong, {name}!\nMen orqali siz ba'zi mahsulotlarni sotib olishingiz mumkin!",
        'welcome_afternoon': "Hayrli kun, {name}!\nMen orqali siz ba'zi mahsulotlarni sotib olishingiz mumkin!",
        'welcome_evening': "Hayrli kech, {name}!\nMen orqali siz ba'zi mahsulotlarni sotib olishingiz mumkin!",
        'products': '🛍 Mahsulotlar',
        'settings': '⚙️ Sozlamalar',
        'categories': '🗓 Kategoriya',
        'support': '📄 Yordam',
        'fruits': '🍏 Mevalar',
        'vegetables': '🥕 Sabzavotlar',
        'milk_products': '🥛 Sut mahsulotlari',
        'meat': '🥩 Go`sht',
        'other_products': '🥗 Boshqa mahsulotlar',
        'Anor': '🔹 Anor',
        'Qurt': '🔹 Qurt',
        'Shaftoli': '🔹 Shaftoli',
        'Muzqaymoq': '🔹 Muzqaymoq',
        'Cheers': '🔹 Cheers',
        'Snickers': '🔹 Snickers',
        'Non': '🔹 Non',
        'Pomidor': '🔹 Pomidor',
        'Nok': '🔹 Nok',
        'Olma': '🔹 Olma',
        'Qaymoq': '🔹 Qaymoq',
        'Sut': '🔹 Sut',
        'Sabzi': '🔹 Sabzi',
        'Bodring': '🔹 Bodring',
        'Kartoshka': '🔹 Kartoshka',
        "Tilni o'zgartirish": "🌐 Tilni o'zgartirish",
        'Dasturchiga yozish': '✏️ Dasturchiga yozish',
        "Ma'lumotnoma": "📄 Ma'lumotnoma",
        'Orqaga': '↩️ Orqaga',
        'Orqaga qaytish': '↩️️ Orqaga qaytish',
        'Menyuga qaytish': '↩️️ Menyuga qaytish',
        'qaytish': '👈 Orqaga',
        'Sotib olish': '💳 Sotib olish',
        "To'lash": "💳 To'lash",
        'Naqd pul': '💸 Naqd pul',
        'Karta orqali': '💳 Karta orqali',
        'Buyurtma berish': '🚚 Buyurtma berish',
        'photo': 'Rasmni ko\'rishim mumkin emas :(',
        "Mol go`shti": "🔹 Mol go`shti",
        "Tovuq go`shti": "🔹 Tovuq go`shti",
        "Qo`y go`shti": "🔹 Qo`y go`shti",
        "Qiyma go`shti": "🔹 Qiyma go`shti(mol)",
        'Marmelad': '🔹 Marmelad',
        'Pechenye': '🔹 Печенье',
        '': '',
        '': '',
        '': '',
        '': '',
        '': '',

    },
    'russian': {
        'welcome_morning': "Доброе утро, {name}!\nЧерез меня вы можете купить некоторые товары!",
        'welcome_afternoon': "Добрый день, {name}!\nЧерез меня вы можете купить некоторые товары!",
        'welcome_evening': "Добрый вечер, {name}!\nЧерез меня вы можете купить некоторые товары!",
        'products': '🛍 Продукты',
        'settings': '⚙️ Настройки',
        'categories': '🗓 Категория',
        'support': '📄 Помощь',
        'fruits': '🍏 Фрукты',
        'vegetables': '🥕 Овощи',
        'milk_products': '🥛 Молочные продукты',
        'meat': '🥩 Мясо',
        'other_products': '🥗 Другие продукты',
        'Anor': '🔹 Гранат',
        'Qurt': '🔹 Курт',
        'Shaftoli': '🔹 Персик',
        'Muzqaymoq': '🔹 Мороженое',
        'Cheers': '🔹 Cheers',
        'Snickers': '🔹 Snickers',
        'Yopgan non': '🔹 Лепёшка',
        'Pomidor': '🔹 Помидор',
        'Nok': '🔹 Груша',
        'Olma': '🔹 Яблоко',
        'Qaymoq': '🔹 Сливки',
        'Sut': '🔹 Молоко',
        'Sabzi': '🔹 Морковь',
        'Bodring': '🔹 Огурец',
        'Kartoshka': '🔹 Картофель',
        "Tilni o'zgartirish": '🌐 Изменить язык',
        'Dasturchiga yozish': '✏️ Написать разработчику',
        "Ma'lumotnoma": '📄 Информация',
        'Orqaga': '↩️️ Назад',
        'Orqaga qaytish': '↩️️ Назад',
        'Menyuga qaytish': '↩️️ Вернуться в меню',
        'qaytish': '👈 Назад',
        'Sotib olish': '💳 Купить',
        "To'lash": '💳 Платить',
        'Naqd pul': '💸 Наличные',
        'Karta orqali': '💳 Через карту',
        'Buyurtma berish': '🚚 Заказать',
        'photo': 'Я не могу увидеть картинку :(',
        "Mol go`shti": '🔹 Говядина',
        "Tovuq go`shti": '🔹 Куриное мясо',
        "Qo`y go`shti": '🔹 Баранина',
        "Qiyma go`shti": '🔹 Говяжий Фарш',
        'Marmelad': '🔹 Мармелад',
        'Pechenye': '🔹 Печенье',
        '': '',
        '': '',
        '': '',
        '': '',
        '': '',

    }
}


